import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Ensure the environments directory exists
const envDirectory = path.join(__dirname, "../src/environments");
if (!fs.existsSync(envDirectory)) {
  fs.mkdirSync(envDirectory, { recursive: true });
}

// Load environment variables from .env file for local development
const envPath = path.resolve(__dirname, "..", ".env");
let localEnv = {};

if (fs.existsSync(envPath)) {
  try {
    const envContent = fs.readFileSync(envPath, "utf-8");
    envContent.split("\n").forEach((line) => {
      const match = line.match(/^([^=]+)=(.*)$/);
      if (match) {
        const key = match[1].trim();
        const value = match[2].trim().replace(/^['"]|['"]$/g, ""); // Remove quotes if present
        localEnv[key] = value;
      }
    });
    console.log("Loaded environment variables from .env");
  } catch (error) {
    console.error("Error reading .env file:", error);
  }
}

// Get the Formspree ID from the environment (Vercel) or local .env
const formspreeId =
  process.env.FORMSPREE_ID || localEnv.FORMSPREE_ID || "FORMSPREE_ID_NOT_SET";

const envConfigFile = `// This file is auto-generated by scripts/set-env.js
export const environment = {
  production: true,
  formspreeId: '${formspreeId}'
};
`;

const targetPath = path.join(envDirectory, "environment.ts");

fs.writeFileSync(targetPath, envConfigFile);

console.log(`Output generated at ${targetPath}`);
console.log(
  `Using Formspree ID: ${
    formspreeId === "FORMSPREE_ID_NOT_SET"
      ? "NOT SET (Check .env or System Vars)"
      : "******"
  }`
);
