import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Ensure the environments directory exists
const envDirectory = path.join(__dirname, "../src/environments");
if (!fs.existsSync(envDirectory)) {
  fs.mkdirSync(envDirectory, { recursive: true });
}

// Get the Formspree ID from the environment, or use a placeholder for dev if missing
// In Vercel, this will be populated from the Environment Variables settings.
const formspreeId = process.env.FORMSPREE_ID || "FORMSPREE_ID_NOT_SET";

const envConfigFile = `// This file is auto-generated by scripts/set-env.js
export const environment = {
  production: true,
  formspreeId: '${formspreeId}'
};
`;

const targetPath = path.join(envDirectory, "environment.ts");

fs.writeFileSync(targetPath, envConfigFile);

console.log(`Output generated at ${targetPath}`);
console.log(
  `Using Formspree ID: ${
    formspreeId === "FORMSPREE_ID_NOT_SET"
      ? "NOT SET (Check .env or System Vars)"
      : "******"
  }`
);
